# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='../keepcoding-django-media'),
        ),
    ]
