# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170320_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
