# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
