# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20170320_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='_Tagulous_Post_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_post_category',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', to='blogs._Tagulous_Post_category'),
        ),
    ]
