# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 15:20
from __future__ import unicode_literals
from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
